### ISSUE TITLE
Open to a PR with some improvements?

### ISSUE THREAD

**Issue by tghamm** [mahdighorbanpour/serilog-sinks-azurecosmosdb#2]
Hi, thank you for your work on this sink.  I came across it, but noticed a few issues, and have made some changes that I think will make it more stable and work like some of the more popular sinks.  Would you be open to a PR if I submitted it for review?

Thanks so much!

Grant

**Comment by mahdighorbanpour** [comment]
Hi @tghamm Thanks for your contribution.
